CREATE TABLE ZIPCODES_USA
(
  AREA_NAME varchar,
AREA_CODE varchar,
DISTRICT_NAME varchar,
DISTRICT_NO integer,
DELIVERY_ZIPCODE integer,
LOCALE_NAME varchar,
PHYSICAL_DELV_ADDR varchar,
PHYSICAL_CITY varchar,
PHYSICAL_STATE varchar,
PHYSICAL_ZIP integer,
PHYSICAL_ZIP_4 integer
);

ALTER TABLE ZIPCodes_USA ADD COLUMN LOCATION_HASH VARCHAR;

UPDATE ZIPCodes_USA SET LOCATION_HASH = UPPER(CONCAT(LEFT(REPLACE(PHYSICAL_DELV_ADDR, ' ', ''), 8), DELIVERY_ZIPCODE));

CREATE INDEX IDX_ZIPCODES_USA_LOCATION_HASH ON ZIPCODES_USA(LOCATION_HASH);

 grant select on public.zipcodes_usa to psypherus;