-- OCTOBER 2022
DROP TABLE IF EXISTS QVF_20221001_V;
CREATE TABLE QVF_20221001_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

ALTER TABLE QVF_20221001_V ADD COLUMN VOTER_OID SERIAL;
ALTER TABLE QVF_20221001_V ADD COLUMN LOCATION_HASH VARCHAR;
ALTER TABLE QVF_20221001_V ADD COLUMN LOCATION_HASH_FULL VARCHAR;
UPDATE QVF_20221001_V SET LOCATION_HASH = UPPER(CONCAT(LEFT(REPLACE(CONCAT(STREET_NUMBER_PREFIX, STREET_NUMBER, DIRECTION_PREFIX, STREET_NAME, STREET_TYPE), ' ', ''), 9), ZIP_CODE));
UPDATE QVF_20221001_V SET LOCATION_HASH_FULL = UPPER(concat(state, left(replace(concat(street_number, direction_prefix, street_name, street_type), ' ', ''), 8), replace(city, ' ', ''), zip_code));
ALTER TABLE IF EXISTS public.QVF_20221001_V
    ADD CONSTRAINT QVF_20221001_V_pkey PRIMARY KEY (voter_oid);

DROP TABLE IF EXISTS QVF_20221001_VH;
CREATE TABLE QVF_20221001_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- SEPTEMBER 2022
DROP TABLE IF EXISTS QVF_20220901_V;
CREATE TABLE QVF_20220901_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

ALTER TABLE QVF_20220901_V ADD COLUMN VOTER_OID SERIAL;
ALTER TABLE QVF_20220901_V ADD COLUMN LOCATION_HASH VARCHAR;
ALTER TABLE QVF_20220901_V ADD COLUMN LOCATION_HASH_FULL VARCHAR;
UPDATE QVF_20220901_V SET LOCATION_HASH = UPPER(CONCAT(LEFT(REPLACE(CONCAT(STREET_NUMBER_PREFIX, STREET_NUMBER, DIRECTION_PREFIX, STREET_NAME, STREET_TYPE), ' ', ''), 9), ZIP_CODE));
UPDATE QVF_20220901_V SET LOCATION_HASH_FULL = UPPER(concat(state, left(replace(concat(street_number, direction_prefix, street_name, street_type), ' ', ''), 8), replace(city, ' ', ''), zip_code));
ALTER TABLE IF EXISTS public.qvf_20220901_v
    ADD CONSTRAINT qvf_20220901_v_pkey PRIMARY KEY (voter_oid);

DROP TABLE IF EXISTS QVF_20220901_VH;
CREATE TABLE QVF_20220901_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- AUGUST 2022
DROP TABLE IF EXISTS QVF_20220801_V;
CREATE TABLE QVF_20220801_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

ALTER TABLE QVF_20220801_V ADD COLUMN VOTER_OID SERIAL;
ALTER TABLE QVF_20220801_V ADD COLUMN LOCATION_HASH VARCHAR;
UPDATE QVF_20220801_V SET LOCATION_HASH = UPPER(concat(left(replace(concat(street_number, direction_prefix, street_name, street_type), ' ', ''), 8), zip_code));
--UPDATE QVF_20220801_V SET LOCATION_HASH = UPPER(concat(state, left(replace(concat(street_number, direction_prefix, street_name, street_type), ' ', ''), 8), replace(city, ' ', ''), zip_code));
ALTER TABLE IF EXISTS public.qvf_20220801_v
    ADD CONSTRAINT qvf_20220801_v_pkey PRIMARY KEY (voter_oid);

DROP TABLE IF EXISTS QVF_20220801_VH;
CREATE TABLE QVF_20220801_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- JULY 2022
DROP TABLE IF EXISTS QVF_20220701_V;
CREATE TABLE QVF_20220701_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

ALTER TABLE QVF_20220701_V ADD COLUMN VOTER_OID SERIAL;
ALTER TABLE QVF_20220701_V ADD COLUMN LOCATION_HASH VARCHAR;
UPDATE QVF_20220701_V SET LOCATION_HASH = UPPER(concat(state, left(replace(concat(street_number, direction_prefix, street_name, street_type), ' ', ''), 8), replace(city, ' ', ''), zip_code));
ALTER TABLE IF EXISTS public.qvf_20220701_v
    ADD CONSTRAINT qvf_20220701_v_pkey PRIMARY KEY (voter_oid);

DROP TABLE IF EXISTS QVF_20220701_VH;
CREATE TABLE QVF_20220701_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- JUNE 2022
DROP TABLE IF EXISTS QVF_20220601_V;
CREATE TABLE QVF_20220601_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

ALTER TABLE QVF_20220601_V ADD COLUMN VOTER_OID SERIAL;
ALTER TABLE QVF_20220601_V ADD COLUMN LOCATION_HASH VARCHAR;
UPDATE QVF_20220601_V SET LOCATION_HASH = UPPER(concat(state, left(replace(concat(street_number, direction_prefix, street_name, street_type), ' ', ''), 8), replace(city, ' ', ''), zip_code));
ALTER TABLE IF EXISTS public.qvf_20220601_v
    ADD CONSTRAINT qvf_20220601_v_pkey PRIMARY KEY (voter_oid);

DROP TABLE IF EXISTS QVF_20220601_VH;
CREATE TABLE QVF_20220601_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- MAY 2022
DROP TABLE IF EXISTS QVF_20220501_V;
CREATE TABLE QVF_20220501_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

ALTER TABLE QVF_20220501_V ADD COLUMN VOTER_OID SERIAL;
ALTER TABLE QVF_20220501_V ADD COLUMN LOCATION_HASH VARCHAR;
ALTER TABLE IF EXISTS public.qvf_20220501_v
    ADD CONSTRAINT qvf_20220501_v_pkey PRIMARY KEY (voter_oid);

DROP TABLE IF EXISTS QVF_20220501_VH;
CREATE TABLE QVF_20220501_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- APRIL 2022
DROP TABLE IF EXISTS QVF_20220401_V;
CREATE TABLE QVF_20220401_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20220401_VH;
CREATE TABLE QVF_20220401_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- MARCH 2022
DROP TABLE IF EXISTS QVF_20220301_V;
CREATE TABLE QVF_20220301_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20220301_VH;
CREATE TABLE QVF_20220301_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- FEBRUARY 2022
DROP TABLE IF EXISTS QVF_20220201_V;
CREATE TABLE QVF_20220201_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20220201_VH;
CREATE TABLE QVF_20220201_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- JANUARY 2022
DROP TABLE IF EXISTS QVF_20220101_V;
CREATE TABLE QVF_20220101_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20220101_VH;
CREATE TABLE QVF_20220101_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- DECEMBER 2021
DROP TABLE IF EXISTS QVF_20211201_V;
CREATE TABLE QVF_20211201_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20211201_VH;
CREATE TABLE QVF_20211201_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- OCTOBER 2021
DROP TABLE IF EXISTS QVF_20211001_V;
CREATE TABLE QVF_20211001_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20211001_VH;
CREATE TABLE QVF_20211001_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- APRIL 2021
DROP TABLE IF EXISTS QVF_20210401_V;
CREATE TABLE QVF_20210401_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20210401_VH;
CREATE TABLE QVF_20210401_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- JANUARY 2021
DROP TABLE IF EXISTS QVF_20210101_V;
CREATE TABLE QVF_20210101_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20210101_VH;
CREATE TABLE QVF_20210101_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);


-- DECEMBER 2020
DROP TABLE IF EXISTS QVF_20201201_V;
CREATE TABLE QVF_20201201_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20201201_VH;
CREATE TABLE QVF_20201201_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- NOVEMBER 2020
DROP TABLE IF EXISTS QVF_20201101_V;
CREATE TABLE QVF_20201101_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20201101_VH;
CREATE TABLE QVF_20201101_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- OCTOBER 2020
DROP TABLE IF EXISTS QVF_20201001_V;
CREATE TABLE QVF_20201001_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20201001_VH;
CREATE TABLE QVF_20201001_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- JUNE 2020
DROP TABLE IF EXISTS QVF_20200601_V;
CREATE TABLE QVF_20200601_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20200601_VH;
CREATE TABLE QVF_20200601_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- MARCH 2020
DROP TABLE IF EXISTS QVF_20200301_V;
CREATE TABLE QVF_20200301_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20200301_VH;
CREATE TABLE QVF_20200301_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- OCTOBER 2019
DROP TABLE IF EXISTS QVF_20191001_V;
CREATE TABLE QVF_20191001_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20191001_VH;
CREATE TABLE QVF_20191001_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);

-- JANUARY 2019
DROP TABLE IF EXISTS QVF_20190101_V;
CREATE TABLE QVF_20190101_V
(	
    LAST_NAME varchar,
    FIRST_NAME varchar,
    MIDDLE_NAME varchar,
    NAME_SUFFIX varchar,
    YEAR_OF_BIRTH integer,
    GENDER varchar,
    REGISTRATION_DATE date,
    STREET_NUMBER_PREFIX varchar,
    STREET_NUMBER varchar,
    STREET_NUMBER_SUFFIX varchar,
    DIRECTION_PREFIX varchar,
    STREET_NAME varchar,
    STREET_TYPE varchar,
    DIRECTION_SUFFIX varchar,
    EXTENSION varchar,
    CITY varchar,
    STATE varchar,
    ZIP_CODE INTEGER,
    MAILING_ADDRESS_LINE_ONE varchar,
    MAILING_ADDRESS_LINE_TWO varchar,
    MAILING_ADDRESS_LINE_THREE varchar,
    VOTER_IDENTIFICATION_NUMBER bigint,
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    PRECINCT VARCHAR,
    WARD VARCHAR,
    IS_PERMANENT_ABSENTEE_VOTER VARCHAR,
    VOTER_STATUS_TYPE_CODE VARCHAR,
    UOCAVA_STATUS_CODE VARCHAR,
    UOCAVA_STATUS_NAME VARCHAR
);

DROP TABLE IF EXISTS QVF_20190101_VH;
CREATE TABLE QVF_20190101_VH
(
    VOTER_IDENTIFICATION_NUMBER BIGINT,		
    COUNTY_NAME VARCHAR,
    JURISDICTION_NAME VARCHAR,
    ELECTION_DATE DATE NOT NULL,
    IS_ABSENTEE_VOTER VARCHAR
);



