module.exports = app => {
  const db = require('../queries/common-queries');

  app.get('/api/qvfdates', db.getQvfDates);
  app.get('/api/counties', db.getCounties); 
  app.get('/api/jurisdictions/:county_name/', db.getJurisdictions);  
  app.get('/api/precincts/:county_name/:jurisdiction_name', db.getPrecincts);  

  /* All Counties */
  app.get('/api/all-counties', (request, response) => {
    response.json([
      { county_id: "-1", county_name: '--- SELECT COUNTY ---'},
      { county_id: "1", county_name: 'ALCONA'},
      { county_id: "2", county_name: 'ALGER'},
      { county_id: "3", county_name: 'ALLEGAN'},
      { county_id: "4", county_name: 'ALPENA'},
      { county_id: "5", county_name: 'ANTRIM'},
      { county_id: "6", county_name: 'ARENAC'},
      { county_id: "7", county_name: 'BARAGA'},
      { county_id: "8", county_name: 'BARRY'},
      { county_id: "9", county_name: 'BAY'},
      { county_id: "10", county_name: 'BENZIE'},
      { county_id: "11", county_name: 'BERRIEN'},
      { county_id: "12", county_name: 'BRANCH'},
      { county_id: "13", county_name: 'CALHOUN'},
      { county_id: "14", county_name: 'CASS'},
      { county_id: "15", county_name: 'CHARLEVOIX'},
      { county_id: "16", county_name: 'CHEBOYGAN'},
      { county_id: "17", county_name: 'CHIPPEWA'},
      { county_id: "18", county_name: 'CLARE'},
      { county_id: "19", county_name: 'CLINTON'},
      { county_id: "20", county_name: 'CRAWFORD'},
      { county_id: "21", county_name: 'DELTA'},
      { county_id: "22", county_name: 'DICKINSON'},
      { county_id: "23", county_name: 'EATON'},
      { county_id: "24", county_name: 'EMMET'},
      { county_id: "25", county_name: 'GENESEE'},
      { county_id: "26", county_name: 'GLADWIN'},
      { county_id: "27", county_name: 'GOGEBIC'},
      { county_id: "28", county_name: 'GRAND TRAVERSE'},
      { county_id: "29", county_name: 'GRATIOT'},
      { county_id: "30", county_name: 'HILLSDALE'},
      { county_id: "31", county_name: 'HOUGHTON'},
      { county_id: "32", county_name: 'HURON'},
      { county_id: "33", county_name: 'INGHAM'},
      { county_id: "34", county_name: 'IONIA'},
      { county_id: "35", county_name: 'IOSCO'},
      { county_id: "36", county_name: 'IRON'},
      { county_id: "37", county_name: 'ISABELLA'},
      { county_id: "38", county_name: 'JACKSON'},
      { county_id: "39", county_name: 'KALAMAZOO'},
      { county_id: "40", county_name: 'KALKASKA'},
      { county_id: "41", county_name: 'KENT'},
      { county_id: "42", county_name: 'KEWEENAW'},
      { county_id: "43", county_name: 'LAKE'},
      { county_id: "44", county_name: 'LAPEER'},
      { county_id: "45", county_name: 'LEELANAU'},
      { county_id: "46", county_name: 'LENAWEE'},
      { county_id: "47", county_name: 'LIVINGSTON'},
      { county_id: "48", county_name: 'LUCE'},
      { county_id: "49", county_name: 'MACKINAC'},
      { county_id: "50", county_name: 'MACOMB'},
      { county_id: "51", county_name: 'MANISTEE'},
      { county_id: "52", county_name: 'MARQUETTE'},
      { county_id: "53", county_name: 'MASON'},
      { county_id: "54", county_name: 'MECOSTA'},
      { county_id: "55", county_name: 'MENOMINEE'},
      { county_id: "56", county_name: 'MIDLAND'},
      { county_id: "57", county_name: 'MISSAUKEE'},
      { county_id: "58", county_name: 'MONROE'},
      { county_id: "59", county_name: 'MONTCALM'},
      { county_id: "60", county_name: 'MONTMORENCY'},
      { county_id: "61", county_name: 'MUSKEGON'},
      { county_id: "62", county_name: 'NEWAYGO'},
      { county_id: "63", county_name: 'OAKLAND'},
      { county_id: "64", county_name: 'OCEANA'},
      { county_id: "65", county_name: 'OGEMAW'},
      { county_id: "66", county_name: 'ONTONAGON'},
      { county_id: "67", county_name: 'OSCEOLA'},
      { county_id: "68", county_name: 'OSCODA'},
      { county_id: "69", county_name: 'OTSEGO'},
      { county_id: "70", county_name: 'OTTAWA'},
      { county_id: "71", county_name: 'PRESQUE ISLE'},
      { county_id: "72", county_name: 'ROSCOMMON'},
      { county_id: "73", county_name: 'SAGINAW'},
      { county_id: "74", county_name: 'ST CLAIR'},
      { county_id: "75", county_name: 'ST JOSEPH'},
      { county_id: "76", county_name: 'SANILAC'},
      { county_id: "77", county_name: 'SCHOOLCRAFT'},
      { county_id: "78", county_name: 'SHIAWASSEE'},
      { county_id: "79", county_name: 'TUSCOLA'},
      { county_id: "80", county_name: 'VAN BUREN'},
      { county_id: "81", county_name: 'WASHTENAW'},
      { county_id: "82", county_name: 'WAYNE'},
      { county_id: "83", county_name: 'WEXFORD'},
    ]);
  });
};